# Site settings
title: "Madhusudan Rajesh"
description: "AI/ML Researcher | Data Scientist | Software Engineer"
baseurl: ""
url: "https://madhusudanrajesh.github.io"

theme: jekyll-theme-minimal
#remote_theme: "mmistakes/minimal-mistakes"

# Footer settings
footer:
  show_email: true
  show_social: true
